version: "3.8"

services:
  postgres :
    image: postgres:15
    ports:
        - "5432:5432"
    environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
       - pg_data:/var/lib/postgresql/data
volumes:
  pg_data: